# Generated by Django 5.2.10 on 2026-09-08 19:19

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foto', '0003_alter_fotobooking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotobooking',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Placering'),
        ),
    ]
