# Generated by Django 5.2.10 on 2026-08-28 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0017_remove_historicalteam_discord_webhook_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qr_code', models.CharField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_map', models.BooleanField(default=True)),
                ('show_points', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loeb_runs', to='organization.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loeb_runs', to='organization.team')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('pin_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('loeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='Loeb.loeb')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('virtual', 'Virtual GPS task'), ('qr', 'QR station task'), ('physical', 'Physical print task'), ('manned', 'Manned station task')], default='physical', max_length=20)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('gps_radius_meters', models.IntegerField(default=30)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('points', models.IntegerField(default=0)),
                ('input_mode', models.CharField(default='none', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='Loeb.task')),
                ('loeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Loeb.loeb')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Loeb.physicalstation')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UNLOCKED', 'Unlocked'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='UNLOCKED', max_length=20)),
                ('submitted_answer', models.TextField(blank=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='Loeb.hold')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='Loeb.task')),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('hold', 'task')},
            },
        ),
    ]
