# Generated by Django 5.2.10 on 2026-08-28 06:53

import map_location.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', 'title']},
        ),
        migrations.AddField(
            model_name='physicalstation',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Lokation'),
        ),
        migrations.AddField(
            model_name='task',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Lokation'),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('virtual', 'Virtuel GPS-opgave'), ('qr', 'QR-station'), ('physical', 'Fysisk print'), ('manned', 'Manned station')], default='physical', max_length=20),
        ),
    ]
