# Generated by Django 5.2.10 on 2026-09-03 21:10

import django.db.models.deletion
import map_location.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loeb', '0002_alter_task_options_physicalstation_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='task',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS-breddegrad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='GPS-længdegrad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='gps_radius_meters',
            field=models.IntegerField(default=30, verbose_name='GPS-radius (meter)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_mode',
            field=models.CharField(default='none', max_length=20, verbose_name='Inputtype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=map_location.fields.LocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Kortplacering'),
        ),
        migrations.AlterField(
            model_name='task',
            name='loeb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Loeb.loeb', verbose_name='Løb'),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='task',
            name='qr_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='QR-kode'),
        ),
        migrations.AlterField(
            model_name='task',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='Loeb.physicalstation', verbose_name='Station'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('virtual', 'Virtuel GPS-opgave'), ('qr', 'QR-station'), ('physical', 'Fysisk opgave'), ('manned', 'Bemandet station')], default='physical', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titel'),
        ),
    ]
