# Generated by Django 5.2.10 on 2026-09-08 19:19

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loeb', '0003_alter_task_description_alter_task_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalstation',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Lokation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Kortplacering'),
        ),
    ]
