# Generated by Django 5.2.10 on 2026-09-08 19:19

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teknik', '0002_remove_teknikbooking_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teknikbooking',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.114951,9.655592', null=True, verbose_name='Lokation'),
        ),
    ]
