# Generated by Django 5.2.10 on 2026-09-08 19:19

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AktivitetsTeam', '0007_alter_aktivitetsteambooking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktivitetsteambooking',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.114951,9.655592', null=True, verbose_name='Lokation'),
        ),
        migrations.AlterField(
            model_name='aktivitetsteamitem',
            name='location',
            field=utils.fields.SafeLocationField(blank=True, default='56.113991,9.665244', null=True, verbose_name='Placering'),
        ),
    ]
