# Generated by Django 5.2.10 on 2026-09-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0003_butikkenorder_butikkenbooking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='butikkenorder',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
