# Generated by Django 5.2.10 on 2026-09-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Butikken', '0004_butikkenorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butikkenorder',
            name='status',
            field=models.CharField(choices=[('Afventer', 'Afventer'), ('Godkendt', 'Godkendt'), ('Afvist', 'Afvist'), ('Pakket', 'Pakket'), ('Udleveret', 'Udleveret')], default='Afventer', max_length=10),
        ),
    ]
